[package]
name = "ko"
version = "0.1.0"
edition = "2021"

[lib]
name = "ko"
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
statrs = "0.16.0"
itertools = "0.11.0"